#!/usr/bin/env python

import sys
import os
import click

SRC_DIR = os.path.join(os.path.dirname(__file__), "src")
sys.path.append(SRC_DIR)


@click.group()
def cli():
    pass


@cli.command()
def assessment_data():
    """
    Insert the assessment forms data.
    """
    from endpoints.commands.assessment_data import assessment_data
    assessment_data()


@cli.command()
def sample_data():
    """
    Insert some sample data for testing.
    """
    from endpoints.commands.sample_data import sample_data
    sample_data()


@cli.command()
def runserver():
    """
    Runs the local testing webserver.
    """
    from endpoints.web.server import runserver
    runserver()


@cli.command()
@click.argument('pytest_args', nargs=-1, type=click.UNPROCESSED)
def runtests(pytest_args):
    """
    Execute the test suite
    """
    from pytest import main
    errno = main(list(pytest_args))
    sys.exit(errno)


if __name__ == "__main__":
    cli()

