ECONOMIC_SECTORS = [
    ("A", "A – Agricultura, silvicultura y pesca"),
    ("B", "B – Explotación de minas y canteras"),
    ("C", "C – Indutrias manufactureras"),
    ("C", "Ca – Industria de alimentación, bebidas y tabaco (C10, C11, C12)"),
    ("C", "Cb – Industria textil, prendas de vestir, cuero y calzado (C13, C14, C15)"),
    ("C", "Cc – Industria de la madera y el corcho; cestería y espartería; papel; artes gráficas y reproducción de soportes grabados"),
    ("C", "Cd – Industria química; coquerías y refino de petróleo; fabricación de productos de caucho y plásticos (C19, C20, C22)"),
    ("C", "Ce – Fabricación de productos farmacéuticos (C21)"),
    ("C", "Cf – Fabricación de otros productos minerales no metálicos (C23)"),
    ("C", "Cg – Metalurgia; fabricación de productos de hierro, acero y ferroaleaciones; fabricación de productos metálicos, excepto maquinaria (C24, C25)"),
    ("C", "Ch – Fabricación de productos informáticos, electrónicos y ópticos; fabricación de material y equipo eléctrico; fabricación de maquinaria y equipo (C26, C27, C28)"),
    ("D", "D – Suministro de electricidad, gas, vapor y aire acondicionado"),
    ("E", "E – Suministro de agua, alcantarillado, gestión de desechos y actividades de saneamiento"),
    ("F", "F – Construcción"),
    ("G", "G – Comercio al por mayor y al por menor, reparación de los vehículos de motor y de las motocicletas"),
    ("H", "H – Transporte y almacenamiento"),
    ("I", "I – Alojamiento y servicios de comida"),
    ("J", "J – Información y comunicación"),
    ("K", "K – Actividades financieras y de seguros"),
    ("L", "L – Actividades inmobiliarias"),
    ("M", "M – Actividades profesionales, científicas y técnicas"),
    ("N", "N – Actividades administrativas y servicios de apoyo"),
    ("O", "O – Administración pública y defensa, planes de seguridad social de afiliación obligatoria"),
    ("P", "P – Enseñanza"),
    ("Q", "Q – Servicios sociales y relacionados con la salud humana"),
    ("R", "R – Artes, entretenimiento y recreación"),
    ("S", "S – Otras actividades de servicio"),
    ("T", "T – Actividades de los hogares en calidad de empleadores, actividades indiferenciadas de producción de bienes y servicios de los hogares para uso propio"),
    ("U", "U – Actividades de organizaciones y órganos extraterritoriales"),
]
