REGIONS = [
    ("WLD", "Promedio global"),
    ("AFR", "África"),
    ("AMO", "Norte de África y Medio Oriente"),
    ("LTN", "Latinoamérica"),
    ("NAO", "Norteamérica y Oceanía"),
    ("ASI", "Asia"),
    ("EUR", "Europa"),
    ("EGY", "Egypt"),
    ("ALB", "Albanien"),
    ("DZA", "Algerien"),
    ("AGO", "Angola"),
    ("ARG", "Argentinien"),
    ("ETH", "Ethiopia"),
    ("AUS", "Australien"),
    ("BHR", "Bahrain"),
    ("BGD", "Bangladesch"),
    ("BEL", "Belgien"),
    ("BOL", "Bolivien"),
    ("BIH", "Bosnien und Herzegovina"),
    ("BWA", "Botswana"),
    ("BRA", "Brasilien"),
    ("BGR", "Bulgarien"),
    ("CHL", "Chile"),
    ("CHN", "China"),
    ("CRI", "Costa Rica"),
    ("DNK", "Denmark"),
    ("DEU", "Germany"),
    ("DOM", "Dominican Republic"),
    ("SLV", "El Salvador"),
    ("CIV", "Côte d'Ivoire"),
    ("ECU", "Ecuador"),
    ("EST", "Estonia"),
    ("FIN", "Finland"),
    ("FRA", "France"),
    ("GEO", "Georgia"),
    ("GHA", "Ghana"),
    ("GRC", "Greece"),
    ("GTM", "Guatemala"),
    ("HND", "Honduras"),
    ("HKG", "Hong Kong SAR, China"),
    ("IND", "India"),
    ("IDN", "Indonesia"),
    ("IRQ", "Iraq"),
    ("IRN", "Iran, Islamic Rep of"),
    ("IRL", "Ireland"),
    ("ISL", "Iceland"),
    ("ISR", "Israel"),
    ("ITA", "Italy"),
    ("JPN", "Japan"),
    ("JOR", "Jordan"),
    ("KHM", "Kambodscha"),
    ("CMR", "Cameroon"),
    ("CAN", "Canada"),
    ("QAT", "Qatar"),
    ("KEN", "Kenya"),
    ("COL", "Colombia"),
    ("COD", "Congo, Dem. Rep."),
    ("COG", "Congo, Dem Republic of"),
    ("HRV", "Croatia"),
    ("LVA", "Latvia"),
    ("LBN", "Lebanon"),
    ("LBY", "Libyan Arab Jamahiriya"),
    ("LTU", "Lithuania"),
    ("MYS", "Malaysia"),
    ("MEX", "Mexico"),
    ("MAR", "Morocco"),
    ("MOZ", "Mozambique"),
    ("MMR", "Myanmar"),
    ("NAM", "Namibia"),
    ("NPL", "Nepal"),
    ("NLD", "Netherlands"),
    ("NGA", "Nigeria"),
    ("NOR", "Norway"),
    ("OMN", "Oman"),
    ("AUT", "Österreich"),
    ("PAK", "Pakistan"),
    ("PAN", "Panama"),
    ("PRY", "Paraguay"),
    ("PER", "Peru"),
    ("PHL", "Philippines"),
    ("POL", "Poland"),
    ("PRT", "Portugal"),
    ("ROU", "Romania"),
    ("RUS", "Russian Federation"),
    ("ZMB", "Zambia"),
    ("SAU", "Saudi Arabia"),
    ("SWE", "Sweden"),
    ("SEN", "Senegal"),
    ("SRB", "Serbia"),
    ("ZWE", "Zimbabwe"),
    ("SGP", "Singapore"),
    ("SVK", "Slovak Republic"),
    ("SVN", "Slovenia"),
    ("ESP", "Spain"),
    ("LKA", "Sri Lanka"),
    ("ZAF", "South Africa"),
    ("SDN", "Sudan"),
    ("KOR", "Korea, Republic of"),
    ("TZA", "Tanzania"),
    ("THA", "Thailand"),
    ("TCD", "Chad"),
    ("CZE", "Czech Republic"),
    ("TUR", "Turkey"),
    ("UGA", "Uganda"),
    ("UKR", "Ukraine"),
    ("HUN", "Hungary"),
    ("URY", "Uruguay"),
    ("VEN", "Venezuela, RB"),
    ("ARE", "United Arab Emirates"),
    ("USA", "United States"),
    ("GBR", "United Kingdom"),
    ("BLR", "Weißrussland"),
]

